spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaee?serverTimezone=Asia/Shanghai
    username: root
    password: sshly

    druid:
      initial-size: 2
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.pan.demo.mapper: debug